### ISSUE TITLE
http://vote.18mr.org/ourvotesmatter/violations/

### ISSUE THREAD

**Issue by seemala** [18mr/vote#11]
![screen shot 2014-10-07 at 11 52 22 pm](https://cloud.githubusercontent.com/assets/8630999/4553693/a22c1d50-4e9e-11e4-9122-77166aa729c8.png)

**Comment by catachresis** [comment]
lol oops

**Comment by catachresis** [comment]
Looks like I had the wrong APIs enabled in my Google Developers Console. I think this should be fixed now.
