### ISSUE TITLE
Landing pg copy under header

### ISSUE THREAD

**Issue by seemala** [18mr/vote#2]
Suggest change from "HAVE YOU REGISTERED TO VOTE IN NOVEMBER?" to "REGISTER TODAY." With "Register Today" linked to https://register2.rockthevote.com/?partner=16591&source=embed-rtv234x60v1 to call up the RTV widget.

Related note, with the exception of the tagline in the header (Activating Asian America), pink text should be consistently linked text. Looks like one of the header styles is pink text (instead of black), which gets confusing from the user perspective.

**Comment by catachresis** [comment]
Fixed!

**Comment by seemala** [comment]
BOOM.
