### ISSUE TITLE
"Voter Guides" page

### ISSUE THREAD

**Issue by seemala** [18mr/vote#3]
As of now, we are only going to definitely have a voter guide for California. I wonder if this page is better labeled "Voter Resources." Guides can be a part of this but we can also put important voter-related info here  — like infographics, PSAs, and the like.

Not saying this change has to happen. I'm curious to hear others' thoughts. Thanks!

**Comment by catachresis** [comment]
"Resources" does seem more all-encompassing, but I think that maybe the PSAs and similar content go elsewhere. If you're already on our site you don't need to be PSA-ed. They seem more like a resource for partners?

**Comment by seemala** [comment]
great  point re: PSAs don't belong there.

maybe it's part of http://vote.18mr.org/partners/promote. it's at promo
asset so... i'll think about this a little more about where, if any place
it belongs. but i think you're right about PSAs not being on the
'resources' page.

C. M. Samala   /   c.samala@gmail.com
Google Voice   /  707 SAMALA C
Twitter  /  samala http://twitter.com/samala
